name: Frames.fun browser extension

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DEV_FRAMES_FUN_API_KEY: "api-key"
      DEV_FRAMES_FUN_API_TRPC_URL: "http://localhost:3000/trpc"
      FARCASTER_HUB_GRPC_URL: "http://localhost:5000"
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - name: Build the extension
        run: pnpm build --filter=extension
      - name: Lint
        run: pnpm lint
